name: Move tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to move'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - v1
      version:
        description: 'Version'
        default: 'v0.0.0'
        required: true
        type: string

jobs:
  release:
    name: Move tag
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Push change to repo
        env:
          INPUT_VERSION: ${{ inputs.version }}
          INPUT_TAG: ${{ inputs.tag }}
        run: |
          git config --global user.email "github@scalr.com"
          git config --global user.name "Github Action"
          HASH=$(git rev-parse "$INPUT_VERSION")
          git tag -fa -m "Move tag to $HASH" "$INPUT_TAG" "$HASH"
          git push -f origin "$INPUT_TAG"
