name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: Scalr/scalr-action@8b36bc5f8a181e792f3caae1039efbdbfdb62f05 # v1.7.1
        with:
          terraform_version: '1.3.7'
          scalr_token: ${{ secrets.SCALR_TOKEN }}
          scalr_hostname: 'test.scalr.io'

      - id: version
        name: Terraform version
        run: terraform -v

      - id: cli-version
        name: Scalr CLI version
        run: scalr -version
